//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitasDigitalSpecFlowCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutUsPageTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUsPageTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualitasDigitalSpecFlowCSharp.src.TestData.AboutUsPageTestData", typeof(AboutUsPageTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is Nicholas Fowler.  I founded Qualitas Digital in 2019 in Wilmington, North Carolina with the mission of bringing affordable, high quality automation to any company looking to elevate their products to the next level.  I have over 15 years experience in the industry at companies large and small, designing solutions that let you scale.  Whether your contract is serviced by myself or other engineers, you can rest easy with the knowledge that solutions will be well researched and implemented with care [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutUsBodyText {
            get {
                return ResourceManager.GetString("AboutUsBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://images.squarespace-cdn.com/content/v1/5dcc96767c939351951d2987/1574119738736-UM33SG724YZEW3FB5PLU/laptop-remote-working-writing-typing-7114.jpg.
        /// </summary>
        internal static string AboutUsImageSrc {
            get {
                return ResourceManager.GetString("AboutUsImageSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A word from our Founder.
        /// </summary>
        internal static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Us Build Something Together.
        /// </summary>
        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/pricing-services.
        /// </summary>
        internal static string OurServicesLink {
            get {
                return ResourceManager.GetString("OurServicesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/schedule-consultation.
        /// </summary>
        internal static string ScheduleConsultationLink {
            get {
                return ResourceManager.GetString("ScheduleConsultationLink", resourceCulture);
            }
        }
    }
}
