//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitasDigitalSpecFlowCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactUsPageData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactUsPageData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualitasDigitalSpecFlowCSharp.src.TestData.ContactUsPageData", typeof(ContactUsPageData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/faq.
        /// </summary>
        internal static string FaqLink {
            get {
                return ResourceManager.GetString("FaqLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Can We Help?.
        /// </summary>
        internal static string HeaderContent {
            get {
                return ResourceManager.GetString("HeaderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to hear from you.  Use the form on the right to request additional information about the services we offer..
        /// </summary>
        internal static string LeftContent {
            get {
                return ResourceManager.GetString("LeftContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/our-commitment.
        /// </summary>
        internal static string OurCommitmentLink {
            get {
                return ResourceManager.GetString("OurCommitmentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/terms-conditions.
        /// </summary>
        internal static string TermsAndConditionsLink {
            get {
                return ResourceManager.GetString("TermsAndConditionsLink", resourceCulture);
            }
        }
    }
}
