//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitasDigitalSpecFlowCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaqPageTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaqPageTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualitasDigitalSpecFlowCSharp.src.TestData.FaqPageTestData", typeof(FaqPageTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We believe we are.  Our solutions reduce future costs as a result of increasing headcounts, increase the value of your employees through training, we even provide direction and structure which increase productivity..
        /// </summary>
        internal static string BodyEight {
            get {
                return ResourceManager.GetString("BodyEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are able to send samples that show an understanding of technologies we use, or training courses we conduct.  In order to protect the Intellectual Property of our clients, we don’t share code or documentation from their projects..
        /// </summary>
        internal static string BodyEleven {
            get {
                return ResourceManager.GetString("BodyEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitas is latin for Quality.  We put quality in our name as it’s at the core of what we do.  We strive to provide efficient and high quality services that stand the test of time..
        /// </summary>
        internal static string BodyFifteen {
            get {
                return ResourceManager.GetString("BodyFifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We start with a free consultation by phone where we talk about the problems facing your company.  We ask clarifying questions to frame the problem and determine whether or not we’re the right choice for you.  Depending on your needs we have one or more follow up meetings where we go into detail about our services, and sign a consulting contract..
        /// </summary>
        internal static string BodyFive {
            get {
                return ResourceManager.GetString("BodyFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of our services.  We have the know-how and experience to assess your business, ask the right questions, and build a custom tailored solution that works for you..
        /// </summary>
        internal static string BodyFour {
            get {
                return ResourceManager.GetString("BodyFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have references available, once we’ve reached the final phase of contract negotiation..
        /// </summary>
        internal static string BodyFourteen {
            get {
                return ResourceManager.GetString("BodyFourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once services have been rendered they are non-refundable.  Regular check ins throughout the project ensure that our work meets your standards so that there are no surprises when the invoice arrives..
        /// </summary>
        internal static string BodyNine {
            get {
                return ResourceManager.GetString("BodyNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide Quality Automation solutions that scale with your business.  Whether you’re creating something from scratch, reworking an existing automation program, or adding to what you have, we work with you to create a customized plan and implement it throughout your business..
        /// </summary>
        internal static string BodyOne {
            get {
                return ResourceManager.GetString("BodyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We pride ourselves on the speed with which we design and implement solutions.  In order to maintain the longevity of the solutions we provide, we work at a pace that avoids sacrificing quality or accuracy..
        /// </summary>
        internal static string BodySeven {
            get {
                return ResourceManager.GetString("BodySeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contract length is entirely dependent on your needs.  Whether you need a consultant for a couple weeks to add tests for a critical feature, or you need a corporate trainer for a year, we’re ready..
        /// </summary>
        internal static string BodySix {
            get {
                return ResourceManager.GetString("BodySix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our consulting agreement includes a defacto Non-Disclosure Agreement.  We value your intellectual property and privacy and protect it the same as our own..
        /// </summary>
        internal static string BodyTen {
            get {
                return ResourceManager.GetString("BodyTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our consultants are experts with industry experience at companies both big and small.  We’ve worked with a variety of technology stacks and continued education is a requirement.  It’s not enough for us to be proficient at one set of technologies, we are continuously evolving what we know so that we remain able to offer the best solutions possible..
        /// </summary>
        internal static string BodyThirteen {
            get {
                return ResourceManager.GetString("BodyThirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two main reasons are time and experience.  It takes time to recruit and train a new employee and verifying they have the experience you need for your business is a constant challenge.  It takes months to recoup the initial recruitment costs.  We deliver value from day one..
        /// </summary>
        internal static string BodyThree {
            get {
                return ResourceManager.GetString("BodyThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re located just outside of Downtown Wilmington in North Carolina.  We use phone and video calls for meetings as needed.  We drive or fly to clients outside of Wilmington regularly to complete work.  We offer a 25% discount on our rates for fully telecommuted work in addition to the money saved on travel expenses..
        /// </summary>
        internal static string BodyTwelve {
            get {
                return ResourceManager.GetString("BodyTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We specialize within the niche of Software Quality Automation.  We have some overlap with traditional Software Automation due to the similarities between disciplines.  We can also automate your workflows and free up time that your employees can use elsewhere..
        /// </summary>
        internal static string BodyTwo {
            get {
                return ResourceManager.GetString("BodyTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/contact-us.
        /// </summary>
        internal static string ContactUsLink {
            get {
                return ResourceManager.GetString("ContactUsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve got questions, we’ve got answers..
        /// </summary>
        internal static string FaqSubtitle {
            get {
                return ResourceManager.GetString("FaqSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        internal static string FaqTitle {
            get {
                return ResourceManager.GetString("FaqTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARE YOU WORTH THE MONEY?.
        /// </summary>
        internal static string TitleEight {
            get {
                return ResourceManager.GetString("TitleEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN YOU SEND US SAMPLES OF YOUR WORK?.
        /// </summary>
        internal static string TitleEleven {
            get {
                return ResourceManager.GetString("TitleEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS THE ORIGIN OF QUALITAS DIGITAL’S NAME?.
        /// </summary>
        internal static string TitleFifteen {
            get {
                return ResourceManager.GetString("TitleFifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT DOES THE CONSULTING PROCESS LOOK LIKE?.
        /// </summary>
        internal static string TitleFive {
            get {
                return ResourceManager.GetString("TitleFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT MAKES YOUR BUSINESS SPECIAL?.
        /// </summary>
        internal static string TitleFour {
            get {
                return ResourceManager.GetString("TitleFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO YOU HAVE REFERENCES?.
        /// </summary>
        internal static string TitleFourteen {
            get {
                return ResourceManager.GetString("TitleFourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS YOUR REFUND POLICY?.
        /// </summary>
        internal static string TitleNine {
            get {
                return ResourceManager.GetString("TitleNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT DOES QUALITAS DIGITAL DO?.
        /// </summary>
        internal static string TitleOne {
            get {
                return ResourceManager.GetString("TitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAN YOU WORK ANY FASTER?.
        /// </summary>
        internal static string TitleSeven {
            get {
                return ResourceManager.GetString("TitleSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW LONG IS A TYPICAL CONTRACT?.
        /// </summary>
        internal static string TitleSix {
            get {
                return ResourceManager.GetString("TitleSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WILL YOU SIGN A NON-DISCLOSURE AGREEMENT?.
        /// </summary>
        internal static string TitleTen {
            get {
                return ResourceManager.GetString("TitleTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT ARE YOUR QUALIFICATIONS?.
        /// </summary>
        internal static string TitleThirteen {
            get {
                return ResourceManager.GetString("TitleThirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY SHOULD WE HIRE A CONSULTANT INSTEAD OF DOING IT ALL OURSELVES?.
        /// </summary>
        internal static string TitleThree {
            get {
                return ResourceManager.GetString("TitleThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE ARE YOU LOCATED, AND HOW DO YOU WORK WITH CLIENTS OUTSIDE OF YOUR LOCAL AREA?.
        /// </summary>
        internal static string TitleTwelve {
            get {
                return ResourceManager.GetString("TitleTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT INDUSTRIES DO YOU SPECIALIZE IN?.
        /// </summary>
        internal static string TitleTwo {
            get {
                return ResourceManager.GetString("TitleTwo", resourceCulture);
            }
        }
    }
}
