//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitasDigitalSpecFlowCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualitasDigitalSpecFlowCSharp.src.TestData.HomePageTestData", typeof(HomePageTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/schedule-consultation.
        /// </summary>
        internal static string FooterScheduleButtonLink {
            get {
                return ResourceManager.GetString("FooterScheduleButtonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s talk!
        ///Your first consultation is free..
        /// </summary>
        internal static string FooterTitle {
            get {
                return ResourceManager.GetString("FooterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Automation shouldn’t be costly or difficult.  Let our Consultants create a road-map for your company that saves you money year after year.
        /// </summary>
        internal static string MidPageTitle {
            get {
                return ResourceManager.GetString("MidPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep up with the latest industry trends and discoveries by checking out our blog..
        /// </summary>
        internal static string MonthlyArticlesSectionBodyText {
            get {
                return ResourceManager.GetString("MonthlyArticlesSectionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/news-notes-qualitas.
        /// </summary>
        internal static string MonthlyArticlesSectionLink {
            get {
                return ResourceManager.GetString("MonthlyArticlesSectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Articles.
        /// </summary>
        internal static string MonthlyArticlesSectionTitle {
            get {
                return ResourceManager.GetString("MonthlyArticlesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re committed to giving you the tools you need to create and scale an automation program that reduces long term headcount, increases the quality and confidence levels of your products, at a price companies large and small can afford..
        /// </summary>
        internal static string OurCommitmentSectionBodyText {
            get {
                return ResourceManager.GetString("OurCommitmentSectionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/our-commitment.
        /// </summary>
        internal static string OurCommitmentSectionLink {
            get {
                return ResourceManager.GetString("OurCommitmentSectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Commitment to You.
        /// </summary>
        internal static string OurCommitmentSectionTitle {
            get {
                return ResourceManager.GetString("OurCommitmentSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer training, coaching, and solutions that save you time and money.  Whether your company has a manual approach, a fully established automation program, or something in between, work with us and gain a competitive advantage..
        /// </summary>
        internal static string OurServicesSectionBodyText {
            get {
                return ResourceManager.GetString("OurServicesSectionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/pricing-services.
        /// </summary>
        internal static string OurServicesSectionLink {
            get {
                return ResourceManager.GetString("OurServicesSectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        internal static string OurServicesSectionTitle {
            get {
                return ResourceManager.GetString("OurServicesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitas Digital brings Software Quality Automation within reach. Our solutions help you bridge the gap between where you are and where you want to be. We help you create Quality Automation programs that scale without the high overhead of a purely manual approach. Whether you need training, coaching, or additional engineers to aid your testing efforts, we have a solution for you. Take advantage of one of our free consultations and learn more about how Qualitas Digital puts the Quality in Software Quality Au [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrimarySectionBodyText {
            get {
                return ResourceManager.GetString("PrimarySectionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://images.squarespace-cdn.com/content/v1/5dcc96767c939351951d2987/1574109947938-NXBEY5PQVS6J657XS2DN/grayscale-photo-of-computer-laptop-near-white-notebook-and-169573.jpg?.
        /// </summary>
        internal static string PrimarySectionImageSrc {
            get {
                return ResourceManager.GetString("PrimarySectionImageSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/schedule-consultation.
        /// </summary>
        internal static string PrimarySectionScheduleButtonLink {
            get {
                return ResourceManager.GetString("PrimarySectionScheduleButtonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting the Quality in Software Quality Automation.
        /// </summary>
        internal static string PrimarySectionTitle {
            get {
                return ResourceManager.GetString("PrimarySectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/about-us.
        /// </summary>
        internal static string SecondarySectionAboutUsButtonLink {
            get {
                return ResourceManager.GetString("SecondarySectionAboutUsButtonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitas Digital was founded to bring scaleable and efficient software quality automation programs to companies large or small. Click the about us link to learn more.Photo by Adil Gökkaya from Pexels.
        /// </summary>
        internal static string SecondarySectionBodyText {
            get {
                return ResourceManager.GetString("SecondarySectionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://images.squarespace-cdn.com/content/v1/5dcc96767c939351951d2987/1574110334562-ACRRQK9X5RP0PMALKYYB/man-holding-laptop-and-smartphone-2726478.jpg.
        /// </summary>
        internal static string SecondarySectionImageSrc {
            get {
                return ResourceManager.GetString("SecondarySectionImageSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Firm.
        /// </summary>
        internal static string SecondarySectionTitle {
            get {
                return ResourceManager.GetString("SecondarySectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have the experience and know-how to help you grow your automation programs. Don’t just take our word for it, see for yourself!.
        /// </summary>
        internal static string TertiarySectionBodyText {
            get {
                return ResourceManager.GetString("TertiarySectionBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/testimonials.
        /// </summary>
        internal static string TertiarySectionClientTestimonialsButtonLink {
            get {
                return ResourceManager.GetString("TertiarySectionClientTestimonialsButtonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://images.squarespace-cdn.com/content/v1/5dcc96767c939351951d2987/1574112242271-KTTBY3ZBBRVYURATJN31/20130731_Trade+100_0202.jpg.
        /// </summary>
        internal static string TertiarySectionImageSrc {
            get {
                return ResourceManager.GetString("TertiarySectionImageSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A High Quality Service.
        /// </summary>
        internal static string TertiarySectionTitle {
            get {
                return ResourceManager.GetString("TertiarySectionTitle", resourceCulture);
            }
        }
    }
}
