//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitasDigitalSpecFlowCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PricingAndServicesPageTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PricingAndServicesPageTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualitasDigitalSpecFlowCSharp.src.TestData.PricingAndServicesPageTestData", typeof(PricingAndServicesPageTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $100/hour- We work within your existing workflow to add additional test coverage.  This is a simple no frills option that adds immediate value to your organization..
        /// </summary>
        internal static string AdditionalTestCoverageBodyText {
            get {
                return ResourceManager.GetString("AdditionalTestCoverageBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Test Coverage.
        /// </summary>
        internal static string AdditionalTestCoverageTitle {
            get {
                return ResourceManager.GetString("AdditionalTestCoverageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $100/hour- We meet with your team and identify areas of growth, pain points, and blockers.  We then work with your team to resolve these issues now and in the future..
        /// </summary>
        internal static string CoachingBodyText {
            get {
                return ResourceManager.GetString("CoachingBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaching.
        /// </summary>
        internal static string CoachingTitle {
            get {
                return ResourceManager.GetString("CoachingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The SaaS Dashboard product is not publicly available at this time.  Keep an eye out for the Beta announcement!.
        /// </summary>
        internal static string DashboardsDisclaimerBodyText {
            get {
                return ResourceManager.GetString("DashboardsDisclaimerBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Premise: $100/hour- We create a custom tailored dashboard that shows the business value and status of your tests.  Depending on the framework and language, we also extend your ‘out of the box’ solutions with additional functionality and value..
        /// </summary>
        internal static string DashboardsOnPremiseBodyText {
            get {
                return ResourceManager.GetString("DashboardsOnPremiseBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software as a Service*: variable cost per user- Sign up for our SaaS Dashboard and enjoy an easy setup and always on functionality at a low cost to you..
        /// </summary>
        internal static string DashboardsSaasBodyText {
            get {
                return ResourceManager.GetString("DashboardsSaasBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        internal static string DashboardsTitle {
            get {
                return ResourceManager.GetString("DashboardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tailored: $150/hour- We create a framework that meets your needs.  This often includes an extensive amount of system specific logging, as well as extensions and documentation that make the framework easy for your engineers to use compared with other frameworks in the industry..
        /// </summary>
        internal static string FrameworkUpdatesCustomTailoredBodyText {
            get {
                return ResourceManager.GetString("FrameworkUpdatesCustomTailoredBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Updates.
        /// </summary>
        internal static string FrameworkUpdatesTitle {
            get {
                return ResourceManager.GetString("FrameworkUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrades/Replacement: $100/hour- Covers all upgrades and updates to existing frameworks such as updating automation to use functionality from a new version or replacing one framework with a different one.  We even perform language changes within existing frameworks such as moving automation from Selenium Java to Selenium C# without the loss of existing tests..
        /// </summary>
        internal static string FrameworkUpdatesUpgradesBodyText {
            get {
                return ResourceManager.GetString("FrameworkUpdatesUpgradesBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.qualitasdigital.com/our-commitment.
        /// </summary>
        internal static string OurCommitmentLink {
            get {
                return ResourceManager.GetString("OurCommitmentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Quality Automation services starting at $100/hour..
        /// </summary>
        internal static string PricingAndServicesSubtitle {
            get {
                return ResourceManager.GetString("PricingAndServicesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing + Services.
        /// </summary>
        internal static string PricingAndServicesTitle {
            get {
                return ResourceManager.GetString("PricingAndServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $125/hour- We analyze your workflows and processes to identify ‘time wasters’ and repetitive tasks that make good candidates for automation.  We document and automate those processes so that your engineers can focus on the things that matter most to you..
        /// </summary>
        internal static string ProcessAutomationBodyText {
            get {
                return ResourceManager.GetString("ProcessAutomationBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Automation.
        /// </summary>
        internal static string ProcessAutomationTitle {
            get {
                return ResourceManager.GetString("ProcessAutomationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $125/hour- We create a 1,3,5 year plan that accomplishes your business objectives.  These plans include multiple versions for Management, and Engineers.  Combined with our other services, this is an effective way to realize your business objectives and communicate them throughout the company..
        /// </summary>
        internal static string RoadmapsBodyText {
            get {
                return ResourceManager.GetString("RoadmapsBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road maps.
        /// </summary>
        internal static string RoadmapsTitle {
            get {
                return ResourceManager.GetString("RoadmapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $250/hour- Our founder helps you create your own startup.  This includes policies and procedures for attracting and hiring talent, the selection and use of initial automation frameworks that match your desired tech stack, training for your senior executives, and quality standards that allow you to maintain a competitive advantage..
        /// </summary>
        internal static string TechnicalCoFounderBodyText {
            get {
                return ResourceManager.GetString("TechnicalCoFounderBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Co-Founder.
        /// </summary>
        internal static string TechnicalCoFounderTitle {
            get {
                return ResourceManager.GetString("TechnicalCoFounderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $100/hour- Personalized training that meets your needs.  Whether you need one on one training, group based training, or a combination of the two, we offer hands on labs and classroom style instruction that brings your engineers up to speed quickly..
        /// </summary>
        internal static string TrainingBodyText {
            get {
                return ResourceManager.GetString("TrainingBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string TrainingTitle {
            get {
                return ResourceManager.GetString("TrainingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $200/hour- Our Founder works alongside your senior executives to scale your software quality operations.  This covers how to attract talent, the technical interview process, and managing your teams..
        /// </summary>
        internal static string TrustedAdvisorBodyText {
            get {
                return ResourceManager.GetString("TrustedAdvisorBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Advisor.
        /// </summary>
        internal static string TrustedAdvisorTitle {
            get {
                return ResourceManager.GetString("TrustedAdvisorTitle", resourceCulture);
            }
        }
    }
}
