//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualitasDigitalSpecFlowCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestimonialsPageData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestimonialsPageData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualitasDigitalSpecFlowCSharp.src.TestData.TestimonialsPageData", typeof(TestimonialsPageData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Cy James.
        /// </summary>
        internal static string HighlightedReviewAuthor {
            get {
                return ResourceManager.GetString("HighlightedReviewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitas Digital created an automation program for our mobile game. We needed something fast so we could develop it with confidence and they really delivered. I was impressed with the attention to detail and how they met with us every step of the way. I can’t recommend them enough!.
        /// </summary>
        internal static string HighlightedReviewContent {
            get {
                return ResourceManager.GetString("HighlightedReviewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others have had this to say….
        /// </summary>
        internal static string MidPageTitle {
            get {
                return ResourceManager.GetString("MidPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — CHARLEY SHAMALY.
        /// </summary>
        internal static string ReviewFiveAuthor {
            get {
                return ResourceManager.GetString("ReviewFiveAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick is one of those rare, detail and data oriented managers that has the wherewithal to think short term yet conceive and execute the vision to think and adapt in to the future. He is exceptionally effective at extracting value adds out of minutia to construct more streamlined processes. His managerial intelligence isn&apos;t limited to &quot;hard science&quot; so-to-speak. He has a deep and genuine concern for his people, their well-being and overall happiness whilst maintaining a fair atmosphere. He can&apos;t be recommende [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReviewFiveContent {
            get {
                return ResourceManager.GetString("ReviewFiveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — MICHELLE KLEEM.
        /// </summary>
        internal static string ReviewFourAuthor {
            get {
                return ResourceManager.GetString("ReviewFourAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick is one of those rare managers who also naturally serves as an inspiring mentor for the whole staff. He is dedicated to his work. With a background in computer science and over 2 years worth of experience as an researcher and adjudications team lead, Nick exhibits strong interpersonal skills and aptitude for accuracy. Nick is the go-to person for conflict resolution and problem solving; when issues arise in the team, he does his best to come up with a successful conclusion. Nick always has respect for o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReviewFourContent {
            get {
                return ResourceManager.GetString("ReviewFourContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — ALEXANDRA WELCH.
        /// </summary>
        internal static string ReviewOneAuthor {
            get {
                return ResourceManager.GetString("ReviewOneAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick was the best manager/team lead I have ever worked for. He was always willing to listen to my concerns with protocols/tasks and work toward a solution that worked for everyone. Every issue that came up was addressed quickly and professionally no matter what it was. He has creative problem solving skills that set him apart from other managers. I cannot stress enough how great it was working with Nick; he was the reason I stayed with the company for as long as I did..
        /// </summary>
        internal static string ReviewOneContent {
            get {
                return ResourceManager.GetString("ReviewOneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — SHRUTI PANDEY.
        /// </summary>
        internal static string ReviewThreeAuthor {
            get {
                return ResourceManager.GetString("ReviewThreeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick is a great team player, he hit the ground running as he joined our team and has been a great addition. He is well-focused, patient, and gives a 100% to any task assigned to him. There were many occasions where his exceptional problem-solving skills and technical sharpness helped immensely. He is always prompt in responding to any situation and proactive in helping out the team mates. Nick&apos;s ability to perform well under pressure, and his willingness to learn and collaborate on any tasks that come his w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReviewThreeContent {
            get {
                return ResourceManager.GetString("ReviewThreeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — JASON LONSBERRY.
        /// </summary>
        internal static string ReviewTwoAuthor {
            get {
                return ResourceManager.GetString("ReviewTwoAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick is great to work with. Not only is he a nice guy but he&apos;s intelligent and hard-working. He picks up new concepts quickly. He&apos;s inquisitive and self-motivated. I knew if Nick was given a problem, it would be thoroughly researched and the solution carefully considered. He was an integral part of our team..
        /// </summary>
        internal static string ReviewTwoContent {
            get {
                return ResourceManager.GetString("ReviewTwoContent", resourceCulture);
            }
        }
    }
}
